### ISSUE TITLE
ATAC ppqt

### ISSUE THREAD

**Issue by schaughencyp** [OpenOmics/chrom-seek#39] opened 2024-05-01 20:18 UTC
For ATAC part,

ppqt can fail causing a lot of downstream issues which can lead to bigwigs not being made. If this not necessary for bigwig formation, this should be removed.

Paul

**Comment by tovahmarkowitz** [comment] 2024-09-17 13:19
Duplicate of another more complete issue

**Closed by tovahmarkowitz** 2024-09-17 13:19 UTC
